# application: sourcebase-a547d
# version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /static
  static_dir: static/
  application_readable: true

- url: .*
  script: main.application
  secure: always

builtins:
- appstats: on

libraries:
- name: ssl
  version: latest

- name: django
  version: "1.5"
  

env_variables:
  DJANGO_SETTINGS_MODULE: 'sourcebase.settings'
  FIREBASE_PROJECT_ID: 'sourcebase-a547d'